### ISSUE TITLE
Cannot find module weak

### ISSUE THREAD

**Issue by plotti** [travist/makemeasandwich.js#13]
➜  ~  makemeasandwich
Logging in.

module.js:340
    throw err;
          ^
Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new D (/usr/local/lib/node_modules/makemeasandwich/node_modules/jquerygo/node_modules/phantom/node_modules/dnode/index.js:28:20)
    at module.exports (/usr/local/lib/node_modules/makemeasandwich/node_modules/jquerygo/node_modules/phantom/node_modules/dnode/index.js:8:12)
    at /usr/local/lib/node_modules/makemeasandwich/node_modules/jquerygo/node_modules/phantom/phantom.js:138:13
    at Server.handler (/usr/local/lib/node_modules/makemeasandwich/node_modules/jquerygo/node_modules/phantom/node_modules/shoe/index.js:22:9)
    at Server.EventEmitter.emit (events.js:95:17)
    at App.emit (/usr/local/lib/node_modules/makemeasandwich/node_modules/jquerygo/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/sockjs.js:182:27)
➜  ~

**Comment by olivierlesnicki** [comment]
Same issue.

**Comment by badrul** [comment]
To fix this, I disable 'weak' by setting it to false.

In jquery.go.js, line #73:

Change: 

```
}, { binary: phantomjs.path });
```

to:

```
}, { 
	binary: phantomjs.path,
	dnodeOpts: {weak: false}
});
```


Ref: https://github.com/amir20/phantomjs-node/blob/master/README.markdown#use-it-in-windows
